### ISSUE TITLE
Not working on Mac OS

### ISSUE THREAD

**Issue by crospa91** [Berny23/LD-ToyPad-Emulator#102]
Hi there, 
First of all thanks for the portal emulator.

Unfortunately tho it's not working on Mac M1, the Portal is correctly connected to the Mac via virtual here but RPCS3 is not able to detect it.

Any idea on what can be done?

LEGO READER V2.10:

  Product ID:	0x0241
  Vendor ID:	0x0e6f
  Version:	5.10
  Serial Number:	P.D.P.000000
  Speed:	Up to 480 Mb/s
  Manufacturer:	PDP LIMITED. 
  Location ID:	0x80100000 / 1
  Current Available (mA):	500
  Current Required (mA):	2
  Extra Operating Current (mA):	0

This is how the Mac identify the portal via virtual here.

**Comment by Berny23** [comment]
The extra steps for RPCS3 are listed here: https://github.com/Berny23/LD-ToyPad-Emulator#rpcs3-cannot-detect-the-toy-pad
However, the tool to replace the driver is only for Windows. I don't own or use any Apple hardware, so I don't know if you can change the Toy Pad's USB driver like on Windows.

**Comment by crospa91** [comment]
Thanks!
