### ISSUE TITLE
I got 20 errors and 2 warnings and I don't know why

### ISSUE THREAD

**Issue by Brandonshev** [Berny23/LD-ToyPad-Emulator#104]
<img width="1100" alt="Screen Shot 2023-01-24 at 11 18 44 pm" src="https://user-images.githubusercontent.com/86109840/214289841-050ee3ab-0b74-4d59-a9a3-5dd568ceee29.png">

for context im using a Raspberry Pi Zero W, macbook pro and a real PS4.
Any help would be greatly appreciated 😊

**Comment by joosthoi1** [comment]
Try running: "sudo apt install libusb-1.0-0-dev -y"

**Comment by Brandonshev** [comment]
> Try running: "sudo apt install libusb-1.0-0-dev -y"

hi thank you for replying, i ran the command and it downloaded but sadly i still have the 2 errors, some things have changed, most noticeable is "`gyp` failed with exit code: 1" is now "`make` failed with exit code: 2" as seen below
<img width="969" alt="Screen Shot 2023-01-28 at 12 41 10 am" src="https://user-images.githubusercontent.com/86109840/215100741-6d693854-05a4-4dc0-9c69-e79c53148031.png">
