### ISSUE TITLE
Missing Characters

### ISSUE THREAD

**Issue by sentrywasbored** [Berny23/LD-ToyPad-Emulator#180]
A few characters seem to be missing from the available character pool, notably the TTG versions of Robin and Cyborg

**Comment by Luigimeansme** [comment]
The TTG versions of Robin and Cyborg are not separate characters, they're transformations accessible from the character wheel for LBM Robin and DC Comics Cyborg once you've entered the TTG world on that file. Same for Fern, both sets of Ghostbusters, Red Lantern Supergirl, the Goonies aside from Sloth, the rest of the A-Team, Jacob Kowalski, and Queenie Goldstein
