### ISSUE TITLE
How do i get the "LD-ToyPad-Emulator" to work on wiiu?

### ISSUE THREAD

**Issue by CubXTub** [Berny23/LD-ToyPad-Emulator#183]
I really wanna use this tool for Lego dimensions on Wii U but I cant find a tutorial or instructions on how to even use this on any console the GitHub page tells me that it works with real Wii U's and all play station console but I cant even find a video on it at all can someone please help me! I might be stupid

**Comment by Luigimeansme** [comment]
The Option 2 section of the tutorial right here on Github is how you use it on real console. You get a single board computer to run the emulator and plug it into the console you want to use

**Comment by CubXTub** [comment]
Yea thank you so much Luigi, I was just being slow.
