### ISSUE TITLE
Help with single board computer

### ISSUE THREAD

**Issue by pj9388** [Berny23/LD-ToyPad-Emulator#189]
I got raspberrypi zero 2 w and everytime I try to install the thing and I get to my 5th step. While the thing is installing on the 5th step it keeps on freezing.

**Comment by pj9388** [comment]
Can someone make a youtube video on how to install it?

**Comment by pj9388** [comment]
![Screenshot_7](https://github.com/Berny23/LD-ToyPad-Emulator/assets/56504660/47bfc5f4-15ea-406b-b966-9415fa23f8a8)

I also have this problem

**Comment by blan44** [comment]
Have you tried following this?
https://github.com/Berny23/LD-ToyPad-Emulator/issues/184#issuecomment-2084768098
