### ISSUE TITLE
Can't find files 

### ISSUE THREAD

**Issue by jhunter999** [Berny23/LD-ToyPad-Emulator#2]
pi@raspberrypi:~ $  sudo cp usb_setup_script.sh /usr/local/bin/toypad_usb_setup.sh
cp: cannot stat 'usb_setup_script.sh': No such file or directory
pi@raspberrypi:~ $  sudo chmod +x /usr/local/bin/toypad_usb_setup.sh
chmod: cannot access '/usr/local/bin/toypad_usb_setup.sh': No such file or directory

This is what pops up when trying to do step 3, don't have any knowledge into code so if you can tell me why it's doing this it would be a big help!

**Comment by Navex** [comment]
You have to clone the repository first before you execute the command to copy `usb_setup_script.sh` the read me is a bit confusing. Just run the commands in this order

```
    sudo apt install -y git
    git clone https://github.com/Berny23/LD-ToyPad-Emulator.git
    cd LD-ToyPad-Emulator
    
    sudo cp usb_setup_script.sh /usr/local/bin/toypad_usb_setup.sh
```

**Comment by Berny23** [comment]
Thanks for the help @Navex!
I think I messed up the command order a bit. Fixing it soon.

**Comment by Navex** [comment]
I made a pull request that fixes it

**Comment by Berny23** [comment]
@Navex Thanks. I didn't see it before closing this issue.
