### ISSUE TITLE
Search By Ability

### ISSUE THREAD

**Issue by Luigimeansme** [Berny23/LD-ToyPad-Emulator#20]
Hi there, just wanted to say first off great job on this project. I've got a Pi Zero W on it's way right now so I can give this a shot, but I had an idea for a new update to this while I'm waiting; a search bar where you can just type in an ability (for example, Boomerang), and get a list of all characters and/or vehicles & gadgets that have it. If at all possible to implement, that could be a really good way to just grab a character you need at a specific point without having to fully memorize what abilities everyone has

**Comment by Berny23** [comment]
I guess, #72 fixed this.
