### ISSUE TITLE
Add labels to Ecto-1's

### ISSUE THREAD

**Issue by Luigimeansme** [Berny23/LD-ToyPad-Emulator#27]
I know they don't do it in-game, but adding 2016 label to at least the new Ecto-1 would make it way easier to tell them apart when there's no images

**Comment by Berny23** [comment]
I already fixed the complete list yesterday, please update the emulator.
Everything is now exactly like in the wiki.

**Comment by Luigimeansme** [comment]
My bad, didn't notice there was an update.
