### ISSUE TITLE
Emulated ToyPad Doesn't See The Game Running.

### ISSUE THREAD

**Issue by Kronos2Day** [Berny23/LD-ToyPad-Emulator#33]
Cannot Use Toypad Emulator, Error?

https://prntscr.com/20x31bo

**Comment by cort1237** [comment]
Verify that VirtualHere is running and that you have double-clicked on the VM in VitualHere. Also start Cemu after starting the Toypad.

**Comment by Kronos2Day** [comment]
I've already tried this, the error is still there, I'll try to install VMWARE

**Comment by Kronos2Day** [comment]
It Worked 👍
