### ISSUE TITLE
Please connect the Toy Pad to the console.

### ISSUE THREAD

**Issue by ScenicGalaxy** [Berny23/LD-ToyPad-Emulator#42]
![issue](https://user-images.githubusercontent.com/98258872/150674487-575782b0-60ce-4a16-888d-cc9d68abf2bb.PNG)
No matter what I try, I cant seem to get cemu to recognize the toy pad. Ive made sure to connect the emulator first, Im using Firefox on Windows. Ive even done the RPCS3 compatibility thing. Now what? any help would be appreciated

**Comment by Berny23** [comment]
Please don't use the RPCS3 solution for Cemu, it breaks everything.
Now, you have to re-install the old driver:

1. Open device manager
2. Scroll down to USB devices and expand it
3. Double-click LEGO READER V2.10
4. Switch to the driver tab
5. Click previous driver
6. Select the first option and click yes
7. Restart Cemu

For Cemu, Zadig should look like this:
![Screenshot 2022-01-23 131419](https://user-images.githubusercontent.com/36038743/150678114-335fe7f5-df16-4e12-99e4-303549e8cf36.png)

For RPCS3, Zadig should look like this:
![Screenshot 2022-01-23 132501](https://user-images.githubusercontent.com/36038743/150678277-8a01b4b5-b57c-4228-86a6-ed3db71c5ece.png)

**Comment by Berny23** [comment]
I've added new troubleshooting sections, maybe they can help you too: https://github.com/Berny23/LD-ToyPad-Emulator#webpage-not-reachable-oracle-virtualbox

**Comment by ScenicGalaxy** [comment]
Big help. It works. thanks

**Comment by yaser900** [comment]
I can't undo the changes on Zadig I tried doing that what you listed but it doesn't seem to be working the driver still is WinUSB and the game still doesn't connect to the toy pad can you help me please?

**Comment by RetroZoneYT** [comment]
im also having this exact problem >_<

**Comment by Patrikipol** [comment]
Same here

**Comment by Nathy2705** [comment]
Ive got the exact same problem, hey berny can you help us?

**Comment by lilkirill101** [comment]
I have a problem that I can't solve( Help me pleaseeeee
![image](https://user-images.githubusercontent.com/122598085/212266755-75edd4d8-52c9-4f5e-89f5-d8604dd712c1.png)
![image](https://user-images.githubusercontent.com/122598085/212268165-26a0bbeb-b1f7-4a76-9bd1-f3558c350669.png)

**Comment by Berny23** [comment]
@lilkirill101 https://github.com/Berny23/LD-ToyPad-Emulator/issues/42#issuecomment-1019474653
