### ISSUE TITLE
Suggestion: PS5 compatibility

### ISSUE THREAD

**Issue by VladimirKuletski** [Berny23/LD-ToyPad-Emulator#45]
Happy to share: works with PS5 (Pi Zero W).
Do you need any photos? Video?

Thanks once again for your work!

**Comment by Berny23** [comment]
That's really nice! :)
I'll make a link to this page in the README file. You can post any video or images here, if you want to.

**Comment by VladimirKuletski** [comment]
![PS5_compatibility](https://user-images.githubusercontent.com/31250777/151259323-4d78c7cb-dd5a-4880-b95e-1a77e06447ca.jpg)

Attached a photo

**Comment by VladimirKuletski** [comment]
@GlitcherFN 
Initially gone through the manual.
Started from PC. Connecting it to PC and check the ID of the emulated device.
Then connecting it to PS5. First was connecting it after the game was started. So it took several times to restart node or reboot to finally appear in the game.
Then I just added autostart to node app. And Pi is always connected to USB.  So while PS5 is starting it boots up and starts node. So, when I'm starting game it's already connected, booted. So game detects it immediately without any issues.

**Comment by GlitcherFN** [comment]
Yeah i figured it out I had to start it before the game was open lol

**Comment by GlitcherFN** [comment]
> @GlitcherFN
> Initially gone through the manual.
> Started from PC. Connecting it to PC and check the ID of the emulated device.
> Then connecting it to PS5. First was connecting it after the game was started. So it took several times to restart node or reboot to finally appear in the game.
> Then I just added autostart to node app. And Pi is always connected to USB. So while PS5 is starting it boots up and starts node. So, when I'm starting game it's already connected, booted. So game detects it immediately without any issues.


How did you add auto start to node?

**Comment by VladimirKuletski** [comment]
Discussed here:
https://github.com/Berny23/LD-ToyPad-Emulator/discussions/51

**Comment by Luigimeansme** [comment]
> I have everything setup it's just the website won't detect the game
> 
> @VladimirKuletski

Make sure you're using a Micro-USB DATA cable, not just one for charging.

**Comment by VladimirKuletski** [comment]
Just to double check: try to connect (boot/start node application) it to PC and verify that it detects as ".. reader".
Might be same issues when USB emulation part is not configured correctly.

**Comment by SONICq101010** [comment]
@Luigimeansme is the data one next to the HDMI

**Comment by SONICq101010** [comment]
@VladimirKuletski how do I verify it?

**Comment by SONICq101010** [comment]
@VladimirKuletski what do you mean?

**Comment by SONICq101010** [comment]
@VladimirKuletski am I supposed to start the game before i start the pi or start the pi first?

**Comment by SONICq101010** [comment]
@Luigimeansme how do I know if it's data or not

**Comment by Luigimeansme** [comment]
> @Luigimeansme how do I know if it's data or not

If you have a phone that uses Micro-USB, plug it into your computer with that cable and see if it allows you to transfer files. If you're not prompted to transfer files, it's a charge only cable and you'll have to get a new one. Try to get one from Amazon, they'll say in the title if it's data supported or not, and they're very cheap

**Comment by SONICq101010** [comment]
I think I have a data one

**Comment by VladimirKuletski** [comment]
> @VladimirKuletski am I supposed to start the game before i start the pi or start the pi first?

Here is how I'm doing it:
1. Turning on PS5
2. Connecting device and waiting till it fully boots and starts program (I've added it to autostart)
3. Opening application website
4. Starting the game on PS5

Attached photo of "proper" port on Pi. I'm just connecting this to PS5
![Emulator_with_cable](https://github.com/Berny23/LD-ToyPad-Emulator/assets/31250777/91bcf4db-2709-41be-b9f7-382207987227)

**Comment by SONICq101010** [comment]
![Uploading 20240130_222412.jpg…]()

**Comment by SONICq101010** [comment]
@VladimirKuletski it didn't work orangeballsmaster is my discord yes its weird but I just need help

**Comment by VladimirKuletski** [comment]
> orangeballsmaster

![image](https://github.com/Berny23/LD-ToyPad-Emulator/assets/31250777/ac33696f-d9e1-4045-b810-1d5967c7c8e0)

**Comment by Gravesurge** [comment]
I have been trying to figure this out, is there a video I can go through??

**Comment by NovaAshwolfDev** [comment]
Damn this issue is still active? it's been two years

**Comment by Gravesurge** [comment]
> Damn this issue is still active? it's been two years

just found this out, but i figured out my issue with the pi, now its saying unexpected syntax error

**Comment by JonasBrinkmann-DE** [comment]
@Gravesurge What kind of syntax error do you get, can you share the full error? Maybe I can help.
