### ISSUE TITLE
Arduino Support?

### ISSUE THREAD

**Issue by GokuWorks** [Berny23/LD-ToyPad-Emulator#5]
Is there any chance this could be done with an Arduino Leonardo?

**Comment by Berny23** [comment]
Maybe, but you'd have to test it. The emulator requires a USB port that can send data and a Linux distro that supports usb_gadgets like the Raspberry OS does.

**Comment by Berny23** [comment]
You won't fit a Linux distro in 28 KB of flash memory.
But if you want to rewrite this emulator in C from scratch and push it to the Arduino, go ahead!
