### ISSUE TITLE
Cemu not recognized

### ISSUE THREAD

**Issue by Whiter645** [Berny23/LD-ToyPad-Emulator#59]
I use Cemu for playing Lego Dimensions because RPCS3 lags too much, i had to do the Zadig workaround to use the emulator on RPCS3, but i did the driver rollback for the Lego READER, now the problem is that the emulator doesn't recognize Cemu, also, my Cemu version is 1.26.2f

**Comment by 3ndgamer28** [comment]
how did you fix this? i have the same problem

**Comment by Whiter645** [comment]
I didn't fix it, the problem still is present (probably, i lost all my files on my hard drive, including Lego Dimension)
