### ISSUE TITLE
does the real toypad and emulated both work at the same time?

### ISSUE THREAD

**Issue by Lego-Dimensions** [Berny23/LD-ToyPad-Emulator#6]
i want to combine the fun of the both and i really am looking into this maybe we could figure it out together?
i know it sounds weird at first but just take a second and think about it, let's say you want to play extremely for fun (like me) when u use all of your minifigures but YOU ARE MISSING THE DAMN character that no-one has it anymore so the only thing is? EmUlAtOr
so if you combine these 2 IT WILL BE DOUBLE FUN!!!

**Comment by Berny23** [comment]
I don't think the game would recognise 2 at the same time. You can try it and post your results here.
