### ISSUE TITLE
game is freezing

### ISSUE THREAD

**Issue by 3ndgamer28** [Berny23/LD-ToyPad-Emulator#64]
idk if this should go here but whenever i get to the cutscene after beating the 1st level it freezes.
help?

**Comment by 3ndgamer28** [comment]
also this is on rpcs3 i havent used cemu yet

**Comment by Berny23** [comment]
Use Vulkan and check my site on the RPCS3 Wiki: https://wiki.rpcs3.net/index.php?title=LEGO_Dimensions

**Comment by 3ndgamer28** [comment]
ok cause vulkan is a default in rpcs3 and also it freezes randomly as it says on the rpcs3 wiki. thanks!
