### ISSUE TITLE
i cant install npm

### ISSUE THREAD

**Issue by The-BreadCat** [Berny23/LD-ToyPad-Emulator#68]
every time i try running npm install it just gets stuck on this message or something similar

[  ................] \ fetchMetadata: sill pacote range manifest for object-inspect@^1.9.0 fetched in 250ms

**Comment by SlightlyPeckish** [comment]
![I too am getting this issue](https://user-images.githubusercontent.com/21175434/170600338-101d67be-4bf5-47e9-b8c3-590c0441d7e0.png)

**Comment by hallinbirch** [comment]
dudes try my "Change one line" fix 
step Zero : open package.json in a IDE or Text editor\
step One :  change the line
"node-ld": "Berny23/node-ld",
To
"node-ld": "https://github.com/Berny23/node-ld.git",
Step Two :
try npm install again
It worked for me and i hope it works for you guys :)

**Comment by The-BreadCat** [comment]
> dudes try my "Change one line" fix step Zero : open package.json in a IDE or Text editor step One : change the line "node-ld": "Berny23/node-ld", To "node-ld": "https://github.com/Berny23/node-ld.git", Step Two : try npm install again It worked for me and i hope it works for you guys :)

**Comment by ignacioat2** [comment]
> dudes try my "Change one line" fix step Zero : open package.json in a IDE or Text editor step One : change the line "node-ld": "Berny23/node-ld", To "node-ld": "https://github.com/Berny23/node-ld.git", Step Two : try npm install again It worked for me and i hope it works for you guys :)

bro how do i open package.json where i can find i in the computer or how can i access it?

**Comment by hallinbirch** [comment]
this issue should have been fixed on june 6th just git the latest comments
and it should work
if you want to change  package.json it should be in the root of the source
i.e. ~/LD-ToyPad-Emulator/package.json or /home/(the username for the
vm)/LD-ToyPad-Emulator/package.json (wherever git cloned the
source)/package.json
