### ISSUE TITLE
Could I do the tutorial using an emulator for the Raspberry?

### ISSUE THREAD

**Issue by vini880** [Berny23/LD-ToyPad-Emulator#7]
Would you have how to do this tutorial using VitualBox emulating the Raspberry?
(sorry for English, I'm Brazilian and I'm using the translator)

**Comment by Berny23** [comment]
I have to experiment a bit with it, but if turns out to be working, I will tell you and update the guide.

**Comment by Berny23** [comment]
Great news for you!
It's now possible to run the emulator in a virtual machine on Windows, macOS and Linux!
I updated the guide and made a tutorial video here: https://www.youtube.com/watch?v=5PARAnrt1jU
