### ISSUE TITLE
No Sign On VirtualHere USB 

### ISSUE THREAD

**Issue by RetroZoneYT** [Berny23/LD-ToyPad-Emulator#79]
So Im Using VMWARE 16 To Do This And i dont see The Lego USB On VirtualHere

**Comment by spudpiggy** [comment]
is the server actually running?

**Comment by AwkwardOne** [comment]
Yeah I got the same issue, I did the troubleshooting thing but still nothing shows up on the VirtualHere

**Comment by spudpiggy** [comment]
It should be working. Try again, make sure that you're properly installing it and that the script is running.
The script needs to run for virtualhere to work.

**Comment by AwkwardOne** [comment]
Yeah my issue was that I had a VPN running in the background.

**Comment by spudpiggy** [comment]
Your problem's solved now? Close the issue.

**Comment by Luigimeansme** [comment]
> Your problem's solved now? Close the issue.

He didn't open this issue, someone else did. Don't be rude
