### ISSUE TITLE
Suggestion: Show abilities for lower vehicle upgrades

### ISSUE THREAD

**Issue by Luigimeansme** [Berny23/LD-ToyPad-Emulator#89]
This is only a slight issue, but it would be nice if upgraded vehicle tokens would be labeled with abilities of their previous forms, so they'd show up under ability search. For example, BMO; BMO will show under the BMO docks ability search, but not DOGMO or SNAKEMO when upgraded, and that's the only way to get that ability so it's slightly annoying. You're able to switch vehicle forms on the fly once they're unlocked, so I see no reason not to show abilities of previous versions.

**Comment by VladimirKuletski** [comment]
Up to you and owner.
Minor thing IMO but might be convenient to someone.
