### ISSUE TITLE
How can I do this on a rooted android phone?

### ISSUE THREAD

**Issue by HamzehTamimi** [Berny23/LD-ToyPad-Emulator#9]
Hello, can you tell me how can I do this on a rooted android phone since I don't own a raspberry pi?

**Comment by Berny23** [comment]
You may be able to do it by enabling the "usb_gadget" feature. It can be done with this app: https://f-droid.org/packages/net.tjado.usbgadget/

**Comment by HamzehTamimi** [comment]
Can you tell me the steps to get it working using a rooted ... Thanks

**Comment by Berny23** [comment]
I don't have a rooted phone available. You can look into the setup script and the code of the emulator to see what features need to be available/working.

**Comment by Berny23** [comment]
It's now possible to run the emulator in a virtual machine on Windows, macOS and Linux!
I updated the guide and made a tutorial video here: https://www.youtube.com/watch?v=5PARAnrt1jU
